export const LOGIN_VERIFICATIONCODE = 'loginVerificationCode'
export const LOGIN_SUBMIT = 'loginSubmit'
export const LOGIN_OUT = 'loginOut'
export const SHOW_BODY_SPIN = 'showBodySpin'
// 账号管理
export const GET_CURRENT_USER_DATA = 'getCurrentUserData'
export const SET_CURRENT_USER_DATA = 'setCurrentUserData'
export const SET_USER_PASSWORD = 'setUserPassword'
export const SET_USER_INFO = 'setUserInfo'
export const MUTATION_MODIFY_USER_INFO = 'modifyUserInfo'
export const GET_USER_LIST_DATA = 'getUserListData'
export const DEL_USER = 'delUser'
export const SET_ROLES_DATA = 'setRolesData'
export const CREAT_NEW_ACCOUNT = 'creatNewAccount'
// 客户管理
export const GET_ADMIN_LIST_DATA = 'getAdminList'
export const GET_CLIENT_LIST_DATA = 'getClientList'
export const CREAT_ADMIN = 'creatAdmin'
export const CREAT_AND_MODIFY_CLIENT = 'creatAndModifyClient'
// 财务管理
export const GET_BILL_LIST = 'getBillList'
export const CONFIRM_BILL_CLEAN = 'confirmBillClean'
export const GET_CLIENT_BALANCE_LIST = 'getClientBalanceList'
export const GET_PAYMENT_LIST = 'getPaymentList'
export const QUERY_CLIENT = 'queryClient'